export class TransportationCost{
    constructor(
	public hrtax_regular_cab?:string,
    public uptax_regular_cab?:string,
    public emp_contrib_regular?:string,
    public gps_regular_cab?:string,
    public gstTax_regular_cab?:string,
    public emp_contrib_shift?:string,
    public gps_shift_cab?:string,
    public gstTax_shift_cab?:string,
    public hrtax_shift_cab?:string,
    public uptax_shift_cab?:string,
    public toll_shift_cab?:string,
    public toll_unscheduled_cab?:string,
    public gstTax_unscheduled?:string,
    public standByCab_extraKms?:string,
    public ratePerKm?:string,
    public extraMileageCost?:string,
    public standByCost?:string,
    public standByTax?:string,
    public otherCabCost?:string,
    public otherCabGST?:string,
    public escortGuardCost?:string,
    public escortGuardDropDutyCost?:string,
    public escortGuardTaxes?:string,
    public tptMobCost?:string,
    public overallUPtax?:string,
    public overallHRtax?:string,
    public overallTaxes?:string,
    public overallToll?:string,
    public overallGPS?:string,
    public foreignExPrice?:string
    ){}
}