//// TODO: replace 'localhost:8080' with the production domain name....
export const environment = {
  production: true,
  url:                        "http://localhost:8080/NCAB",
  loginUrl:                   this.url + "/EmployeeService/login",
  logoutUrl:                  this.url + "/EmployeeService/logout",
  checkLoginUrl:              this.url + "/EmployeeService/check-login-status",
  addEmployeeUrl:             this.url + "/EmployeeService/add-employee",
  activateEmployeeUrl:        this.url + "/EmployeeService/activate-employee",
  deactivateEmployeeUrl:      this.url + "/EmployeeService/deactivate-employee",
  editEmployeeUrl:            this.url + "/EmployeeService/edit-employee",
  viewEmployeeUrl:            this.url + "/EmployeeService/view-employee",
  getManagerByNameUrl:        this.url + "/EmployeeService/get-manager-by-name",
  getAllManagersUrl:          this.url + "/EmployeeService/get-all-managers",
  getAllRolesUrl:             this.url + "/EmployeeService/get-all-roles",
  newAccSetupQlidUrl:         this.url + "/EmployeeService/new-acc-setup",
  forgotpasswordUrl:          this.url + "/EmployeeService/forgot-password",
  forgotpassSetPasswordUrl:   this.url + "/EmployeeService/forgot-password/set-password",
  accSetupSetPasswordUrl:     this.url + "/EmployeeService/new-acc-setup/set-password",
  verifyPwdTokenUrl:          this.url + "/EmployeeService/verify-pwd-token",
  getrequestUrl:              this.url + "/RequestService/getrequest",
  allocateRequest:            this.url + "/RequestService/onApproved",
  employeeRequest:            this.url + "/ReportService/employeereport",
  managerUrl:                 this.url + "/ReportService/managerreport",
  vendorUrl:                  this.url + "/ReportService/vendorreport",
};